AWSTemplateFormatVersion: '2010-09-09'
Description: Photo album web application stack
Parameters:
  OpenSearchEndpoint:
    Type: String
    Description: The endpoint URL of the OpenSearch domain used for indexing and search
Resources:
  # S3 Buckets and Bucket Policy
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ["", [ !GetAtt FrontendBucket.Arn, "/*" ]]
  PhotoBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - IndexPhotosFunction
      - IndexPhotosPermission
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedHeaders:
              - "*"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg
            Function: !GetAtt IndexPhotosFunction.Arn
  # Lambda Functions and IAM Roles
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonRekognitionFullAccess
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          OS_HOST: !Ref OpenSearchEndpoint
      Code:
        ZipFile: |
          import boto3
          import json
          import os
          def lambda_handler(event, context):
              # Extract bucket name and key from the S3 event
              records = event.get('Records', [])
              for record in records:
                  bucket = record['s3']['bucket']['name']
                  key = record['s3']['object']['key']
                  print(f"New image uploaded: s3://{bucket}/{key}")
                  # Here, you could call Rekognition to detect labels
                  # e.g., rekognition = boto3.client('rekognition')
                  # labels = rekognition.detect_labels(Image={'S3Object': {'Bucket': bucket, 'Name': key}})
                  # And then index these labels in OpenSearch using OS_HOST
                  # For example, use AWS OpenSearch Python client or requests to send data to OS_HOST
                  print("Image processed and indexed in OpenSearch")
              return {"statusCode": 200, "body": json.dumps({"status": "Image indexed"})}
  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          OS_HOST: !Ref OpenSearchEndpoint
      Code:
        ZipFile: |
          import json
          import os
          def lambda_handler(event, context):
              # Parse query parameter 'q' for search term
              query = None
              params = event.get("queryStringParameters")
              if params and "q" in params:
                  query = params["q"]
              # Here, you could query the OpenSearch domain using OS_HOST and the query term
              results = {"searchTerm": query, "photos": []}
              # Example: results["photos"] = search_open_search(OS_HOST, query)
              # Prepare response with CORS headers
              return {
                  "statusCode": 200,
                  "headers": {
                      "Access-Control-Allow-Origin": "*",
                      "Access-Control-Allow-Headers": "*"
                  },
                  "body": json.dumps(results)
              }
  IndexPhotosPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IndexPhotosFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
  # API Gateway Resources and Methods
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PhotoApi
      BinaryMediaTypes:
        - image/jpeg
      EndpointConfiguration:
        Types:
          - REGIONAL
  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: search
  PhotosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: photos
  SearchMethodGET:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - !Ref AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - !GetAtt SearchPhotosFunction.Arn
            - "/invocations"
  SearchMethodOPTIONS:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SearchResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        PassthroughBehavior: NEVER
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty
  ApiGatewayS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ApiGatewayS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Join ["", [ !GetAtt PhotoBucket.Arn, "/*" ]]
  PhotosMethodPUT:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref PhotosResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: PUT
        Credentials: !GetAtt ApiGatewayS3Role.Arn
        Uri:
          Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - !Ref AWS::Region
            - ":s3:path/"
            - !Ref PhotoBucket
            - "/{objectKey}"
        RequestParameters:
          "integration.request.path.objectKey": "method.request.querystring.objectKey"
        PassthroughBehavior: WHEN_NO_MATCH
      RequestParameters:
        "method.request.querystring.objectKey": true
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
  PhotosMethodOPTIONS:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref PhotosResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        PassthroughBehavior: NEVER
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      Description: "Deployment of API"
    DependsOn:
      - SearchMethodGET
      - SearchMethodOPTIONS
      - PhotosMethodPUT
      - PhotosMethodOPTIONS
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref ApiGatewayRestApi
      DeploymentId: !Ref ApiDeployment
  SearchLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SearchPhotosFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/search"
Outputs:
  FrontendUrl:
    Description: URL of the static photo album website
    Value: !GetAtt FrontendBucket.WebsiteURL
  ApiUrl:
    Description: Base URL of the API Gateway (prod stage)
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
